config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'notifications/index'
  get 'assets/index'
  devise_for :users

  get 'users/:id', to: 'users#show', as: 'show_user'
  delete 'delete_profile_picture', to: 'users#delete_profile_picture', as: 'delete_profile_picture'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assets do
    resources :bookings do
      collection do
        post :create_request
        get :new_request
      end
    end
    collection do
      get :sort_and_filter_assets
      get :wished_assets
    end
    resources :ratings, only: [:index, :create]
    get :add_to_wishlist
    delete :remove_from_wishlist
  end
  resources :bookings, only: [:index, :destroy] do
    collection do
      get :requests
      get 'show_request/:id', to: 'bookings#show_request', as: 'show_request'
      get :requested_assets
      get 'show_request/:request_id/reject_request', to: 'bookings#reject_request', as: 'reject_request'
      get 'show_request/:request_id/accept_request', to: 'bookings#accept_request', as: 'accept_request'
      get :booked_assets
    end
  end
  resources :notes, path: 'notes/:request_id', only: [:create, :index, :destroy]

  get 'my_assets', to: 'users#assets', as: 'my_assets'
  get 'search_option', to: 'assets#get_option_for_search_input', as: 'search_option'
  root 'assets#index'

  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  resources :notifications, only: [:index, :update]

  match '*path', to: "application#render_404", via: :all, constraints: lambda {|req| req.path.exclude? 'rails/active_storage'}
end

app/models/note.rb
class Note < ApplicationRecord
  include Notificable
  belongs_to :request
  validates :content, presence: true
  belongs_to :user
  after_create :send_new_note_notifications_to_user
  def note_to_user_id
    if self.user_id == self.request.requestor_id
      self.request.asset.user_id
    else
      self.request.requestor_id
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def create
    @request = Request.find(params[:request_id])
    @note = @request.notes.build(note_params)
    @note.user = current_user
    if @note.save
      flash[:success] = "Note successfully added"
      redirect_to show_request_bookings_path(@request)
    else
      flash[:danger] = "Request couldn't be saved"
      redirect_to show_request_bookings_path(@request)
    end
  end

  def destroy
    @note = Note.find(params[:id])
    authorize @note
    if @note.destroy
      flash[:success] = 'Note has been successfully deleted.'
      redirect_to show_request_bookings_path(params[:request_id])
    else
      flash[:error] = 'Unable to delete the request'
      redirect_to show_request_bookings_path(params[:request_id])
    end
  end
  
  private

  def note_params
    params.require(:note).permit(:content)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  
end

app/views/notes/_new_note.html.erb
<div class="collapse" id="add_note_container">
  <%= form_for :note, url: notes_path(@request) do |f| %>
    <div class="form-group">
      <%= f.label :content, "Your message:" %>
      <%= f.text_area :content, class: "form-control", row: 2 %>
    </div>
    <%= f.submit "Add message", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/notes/_note.html.erb
<div class="note-container">
  <strong> <%= "#{note.user.first_name} #{note.user.last_name}" %> </strong>
  <div class="row">
    <div class="col-sm-10"><p> <%= note.content %> </p></div>
    <% if policy(note).destroy? %>
      <div class="col-sm-2">
        <%= link_to note_path(note.request_id, note.id), method: :delete, class: "text-red-md right-align" do %>
          <span class="fa fa-trash">Delete</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>