config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'notifications/index'
  get 'assets/index'
  devise_for :users

  get 'users/:id', to: 'users#show', as: 'show_user'
  delete 'delete_profile_picture', to: 'users#delete_profile_picture', as: 'delete_profile_picture'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assets do
    resources :bookings do
      collection do
        post :create_request
        get :new_request
      end
    end
    collection do
      get :sort_and_filter_assets
      get :wished_assets
    end
    resources :ratings, only: [:index, :create]
    get :add_to_wishlist
    delete :remove_from_wishlist
  end
  resources :bookings, only: [:index, :destroy] do
    collection do
      get :requests
      get 'show_request/:id', to: 'bookings#show_request', as: 'show_request'
      get :requested_assets
      get 'show_request/:request_id/reject_request', to: 'bookings#reject_request', as: 'reject_request'
      get 'show_request/:request_id/accept_request', to: 'bookings#accept_request', as: 'accept_request'
      get :booked_assets
    end
  end
  resources :notes, path: 'notes/:request_id', only: [:create, :index, :destroy]

  get 'my_assets', to: 'users#assets', as: 'my_assets'
  get 'search_option', to: 'assets#get_option_for_search_input', as: 'search_option'
  root 'assets#index'

  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  resources :notifications, only: [:index, :update]

  match '*path', to: "application#render_404", via: :all, constraints: lambda {|req| req.path.exclude? 'rails/active_storage'}
end

app/models/booking.rb
class Booking < ApplicationRecord
  #include Notificable
  belongs_to :asset
  belongs_to :request
  belongs_to :user

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  before_action :check_user, only: [:new_request, :create_request]
  before_action unless: :user_signed_in?, only: [:index, :requested_assets, :requests] do
    redirect_to new_user_session_path
  end

  def index
    @assets = current_user.assets_booked_by_user
  end

  def booked_assets
    @assets = current_user.booked_assets_of_user
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @asset = @booking.asset
    @asset.update(available: true)
    @booking.request.change_status_to_pending_for_non_expired_requests(@booking.asset_id)
    SendCancelBookingNotificationJob.perform_later(to_user_id(@booking.request), @asset, "Booking for #{@asset.name} cancelled by #{current_user.first_name}")
    
    if @booking.request.destroy
      flash[:success] = "Booking has been successfully cancelled"
      redirect_to asset_path(@asset)
    else
      flash[:danger] = "Unable to cancel booking"
      redirect_to asset_path(@asset)
    end
  end

  def new_request
    @request = Asset.find(params[:asset_id]).requests.build
  end

  def create_request
    @asset = Asset.find(params[:asset_id])
    @request = @asset.requests.build(request_params)
    @request.requested_price_info = @asset.currency + @asset.price.to_s + " " + @asset.payment_period
    @request.requestor = current_user
    if @request.save
      flash[:success] = "Request is sent to the owner successfully"
      redirect_to assets_path
    else
      flash[:danger] = "Unable to save request!"
      render 'new_request'
    end
  end

  def requested_assets
    @assets = current_user.assets
  end

  def show_request
    @request = Request.find(params[:id])
    authorize @request, :show?
  end

  def requests
    @requests = Request.requests_by_user(current_user.id)
  end

  def reject_request
    @request = Request.find(params[:request_id])
    @request.request_status = "rejected"
    authorize @request, :update?
    if @request.save
      flash[:success] = "You have rejected the request"
      redirect_to show_request_bookings_path(params[:request_id])
    else
      flash[:danger] = "Some errors occur while making changes"
      redirect_to show_request_bookings_path(params[:request_id])
    end
  end

  def accept_request
    @request = Request.find(params[:request_id])
    authorize @request, :update?
    @asset = @request.asset
    @booking = @request.build_booking
    @booking.user = @request.requestor
    @booking.asset = @request.asset
    @request.request_status = "accepted"
    ActiveRecord::Base.transaction do
      @request.reject_other_overlapping_pending_requests
      @request.save!
      @asset.save!
      @booking.save!
    end
    flash[:success] = "This requested is accepted"
    redirect_to show_request_bookings_path(@request)
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = "Unable accept request due to some error"
      redirect_to show_request_bookings_path(@request)
  end

  private

  def request_params
    params.require(:request).permit(:event_name, :event_description, :event_start_date, :event_end_date)
  end

  def check_user
    if !user_signed_in?
      flash[:warning] = "Sign-up/Sign-first "
      redirect_to new_user_session_path

    elsif (Asset.find(params[:asset_id]).user.id == current_user.id)
      flash[:danger] = "You are the owner of this asset."
      redirect_to asset_path(params[:asset_id])

    elsif !current_user.phone_verification_status
      flash[:warning] = "Verify your phone number to request"
      redirect_to new_phone_verification_path
    end
  end

  def to_user_id(request)
    if current_user.id.eql?(request.requestor_id)
      request.asset.user_id
    else
      request.requestor_id
    end
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div class="booking-info-container col-sm-3 mr-1">
  <div class="head"> <span class="display-index"> <%= count + 1 %> </span> <strong>Booked by: </strong> <%= link_to "#{booking.user.first_name} #{booking.user.last_name}", show_user_path(booking.user_id) %> </div>
  <div class="body">
    <Strong>For Event:</Strong> <span class="highlight fit"> <%= booking.request.event_name %> </span> <br>
    <strong>Price info:</strong> <%= booking.request.requested_price_info %>
  </div>
  <div class="show-booked-dates">
    <div class="start-date-container">
      <strong>From:</strong>
      <div datetime=<%= booking.request.event_start_date %> class="booked-start-date">
        <div class="booked-day"></div>
        <div class="booked-date"></div>
        <div class="booked-month"></div>
        <div class="booked-year"></div>
      </div>
    </div>
    <div class="end-date-container">
      <strong>To:</strong>
      <div datetime=<%= booking.request.event_end_date %> class="booked-end-date">
        <div class="booked-day"></div>
        <div class="booked-date"></div>
        <div class="booked-month"></div>
        <div class="booked-year"></div>
      </div>
    </div>
  </div>
  <div class="number-of-days"></div>
  <div class="action-buttons">
    <%= link_to('Details', show_request_bookings_path(booking.request_id), class: "btn btn-success btn-sm") %>
    <%= link_to('Cancel', booking_path(booking.id), method: :delete, class: "btn btn-danger btn-sm") if policy(booking).destroy? %>
  </div>
</div>

app/views/bookings/_request.html.erb
<div class="show-request row">
  <div class="col-sm-9">
    For: <strong> <%= link_to request.asset.name, asset_path(request.asset_id) %> </strong>, By: <em> <%= link_to "#{request.requestor.first_name} #{request.requestor.last_name}", show_user_path(request.requestor_id) %> </em><br>
    From: <span class="show-date date-highlight" date=<%= request.event_start_date %>></span>, To: <span class="date-highlight" date=<%= request.event_end_date %>></span> <span class="day-highlight"></span> <br>
    For price: <%= request.requested_price_info %> <br>
    Status: <strong class="request-<%= request.request_status %>"> <%= request.request_status.capitalize %> </strong>
  </div>
  <div class="col-sm-3 text-center">
    <%= link_to 'Show details', show_request_bookings_path(request), class: "btn btn-primary" %>
  </div>
</div>

app/views/bookings/booked_assets.html.erb
<div class="col-sm-11">
  <h3><strong>My booked Assets</strong></h3>
  <hr>
  <% if @assets.any? %>
      <% @assets.each do |asset| %>
        <div class="booked-asset-name"> 
          <span class="asset-icon"> <%= image_tag asset.pictures.first %> </span> 
          <%= link_to asset.name, asset_path(asset.id) %>
        </div>
        <div class="row">
          <% count = 0%>
          <% asset.bookings.each do |booking| %>
            <%= render partial: 'bookings/booking', locals: { booking: booking, count: count }  %>
            <% count += 1 %>
          <% end %>
        </div>
        <hr>
      <% end %>
  <% else %>
    <h4>No assets have been booked yet.</h4>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="col-sm-11">
  <h3>My Booked Assets</h3>
  <hr>
  <% if @assets.any? %>
      <% @assets.each do |asset| %>
        <div class="booked-asset-name"> 
          <span class="asset-icon"> <%= image_tag asset.pictures.first %> </span> 
          <%= link_to asset.name, asset_path(asset.id) %>
        </div>
        <div class="row">
          <% count = 0%>
          <% asset.bookings.each do |booking| %>
            <%= render partial: 'bookings/booking', locals: { booking: booking, count: count }  %>
            <% count += 1 %>
          <% end %>
        </div>
        <hr>
      <% end %>
  <% else %>
    <h4>You haven't booked for anything yet</h4>  
  <% end %>
</div>

app/views/bookings/new_request.html.erb
<div class="text-center"><h3>Request Booking</h3></div> <hr>
<div class="row col-sm-11">
  <div class="col-sm-7" id="booking_request_container">
    <% if @request.errors.any? %>
      <div class="alert alert-danger">
        <%= "Server detects validation errors" %> <br>
        <%= show_validation_error(@request, :user_id) %>
      </div>  
    <% end %>
    <h4>For: <%= link_to @request.asset.name, asset_path(@request.asset_id) %> </h4>
    <div class="highlight"> <h5> <%= "#{@request.asset.currency}#{@request.asset.price} #{@request.asset.payment_period}" %> </h5> </div>
    <%= form_for @request, url: create_request_asset_bookings_path do |f| %>
      <div class="form-group">
        <%= f.label :event_name, "Event Name:" %>
        <%= f.text_field :event_name, class: "form-control", list: "event_tags", required: true %>
        <div class="feedback-warning"><%= show_validation_error(@request, :event_name) %></div>
      </div>

      <div class="form-group">
        <%= f.label :event_description, "Describe the event:" %>
        <%= f.text_area :event_description, class: "form-control", rows: 3, required: true %>
        <div class="feedback-warning"> <%= show_validation_error(@request, :event_description) %> </div>
      </div>

      <div class="form-group">
        <%= f.label :event_start_date, "Starting date of the event" %>
        <%= f.date_field :event_start_date, class: "form-control event-dates", required: true, asset_id: @request.asset_id %>
        <div class="feedback-warning"><%= show_validation_error(@request, :event_start_date) %></div>
      </div>

      <div>
        <%= f.label :event_end_date, "Event Closing date:" %>
        <%= f.date_field :event_end_date, class: "form-control event-dates", required: true, asset_id: @request.asset_id %>
        <div class="feedback-warning"> <%= show_validation_error(@request, :event_end_date) %> </div>
      </div>
      <br>

      <%= f.submit "Request", class: "btn btn-primary", id: "request_btn" %>
    <% end %>
  </div>

  <div class="col-sm-5" id="show_booked_dates">
    <h4>Booked Dates</h4> <hr>
    <% if @request.asset.accepted_requests.any? %>
      <% @request.asset.accepted_requests.each do |request| %>
        Booked For: <h4> <%= request.event_name %> </h4>
        <div class="show-request-date-container">
          <div class="start-date ml-4" datetime=<%= request.event_start_date %>>
            <div class="day"></div>
            <div class="month"></div>
            <div class="date"></div>
            <div class="year"></div>
          </div>
          <div class="end-date ml-5" datetime=<%= request.event_end_date %>>
            <div class="day"></div>
            <div class="month"></div>
            <div class="date"></div>
            <div class="year"></div>
          </div>
        </div>
        <hr>
      <% end %>
    <% else %>
      <h4> This place is not booked for anything yet. </h4>      
    <% end %>
  </div>
</div>

<datalist id="event_tags">
  <%= options_for_select(@request.asset.event_tags) %>
</datalist>

app/views/bookings/requested_assets.html.erb
<div class="container col-sm-10" id="show_requests_container">
  <h3> My Requested Assets </h3> <hr>
  
  <% if @assets.any? %>
    <% @assets.each do |asset| %>
      <% next unless asset.requests.any? %>
      <h5>
        <%= link_to "#{asset.name}" ,asset_path(asset) %>
      </h5> <hr>
      <%= render partial: 'bookings/request', collection: asset.requests %>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/bookings/requests.html.erb
<div class="container col-sm-9" id="show_requests_container">
  <h3> My Requests and status</h3> <hr>
  <% if @requests.any? %>
    <%= render partial: 'bookings/request', collection: @requests %>
    <% else %>
    <h4>You have not requested for anything yet.</h4>  
  <% end %>
  
</div>

app/views/bookings/show_request.html.erb
<div class="row container mr-1 col-sm-11">
  <div class="col-sm-7" id="show_request_container">
    <div class="request-heading">
      <h3>
        For: <%= link_to asset_path(@request.asset) do %>
        <strong> <%= @request.asset.name %> </strong> <% end %>
      </h3>
      <h5> By: <%= link_to "#{@request.requestor.first_name} #{@request.requestor.last_name}", show_user_path(@request.requestor) %> </h5>
      <div class="highlight"> <h5><%= "#{@request.requested_price_info}" %></h5> </div>
    </div>
    <hr>
    <div class="request-body">
      For Event: <p class="inline-style-box"> <%= @request.event_name %> </p>
      <br> <br>
      Description: <br>
      <p><%= @request.event_description %></p>
      <br>

      <div class="show-request-date-container">
        <div class="col-sm-3">
          Event Start Date:
          <div datetime=<%= @request.event_start_date %> class="start-date"> 
            <div class="day"></div>
            <div class="month"></div>
            <div class="date"></div>
            <div class="year"></div>
          </div>
        </div>
        <div class="col-sm-3">
          Event End Date:
          <div datetime=<%= @request.event_end_date %> class="end-date"> 
            <div class="day"></div>
            <div class="month"></div>
            <div class="date"></div>
            <div class="year"></div>
          </div>
        </div>
      </div>
    </div>

    <% if policy(@request).update? %>
      <div class="col-sm-6 ml-auto mt-1">
        <%= link_to 'Reject', reject_request_bookings_path(@request), class: "btn btn-danger" %>
        <%= link_to 'Accept', accept_request_bookings_path(@request), class: "btn btn-success" %>
      </div>
    <% end %>

  </div>

  <div class="col-sm-5">
    <h4><strong>Notes here</strong></h4> <hr>
    <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#add_note_container"><span class="fa fa-plus-circle">Add notes</span></button>
    <%= render 'notes/new_note' %>
    <% if @request.notes.any? %>
      <div class="notes-container">
        <%= render partial: 'notes/note', collection: @request.notes %>
      </div>  
    <% end %>
  </div>
</div>