config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'notifications/index'
  get 'assets/index'
  devise_for :users

  get 'users/:id', to: 'users#show', as: 'show_user'
  delete 'delete_profile_picture', to: 'users#delete_profile_picture', as: 'delete_profile_picture'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assets do
    resources :bookings do
      collection do
        post :create_request
        get :new_request
      end
    end
    collection do
      get :sort_and_filter_assets
      get :wished_assets
    end
    resources :ratings, only: [:index, :create]
    get :add_to_wishlist
    delete :remove_from_wishlist
  end
  resources :bookings, only: [:index, :destroy] do
    collection do
      get :requests
      get 'show_request/:id', to: 'bookings#show_request', as: 'show_request'
      get :requested_assets
      get 'show_request/:request_id/reject_request', to: 'bookings#reject_request', as: 'reject_request'
      get 'show_request/:request_id/accept_request', to: 'bookings#accept_request', as: 'accept_request'
      get :booked_assets
    end
  end
  resources :notes, path: 'notes/:request_id', only: [:create, :index, :destroy]

  get 'my_assets', to: 'users#assets', as: 'my_assets'
  get 'search_option', to: 'assets#get_option_for_search_input', as: 'search_option'
  root 'assets#index'

  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  resources :notifications, only: [:index, :update]

  match '*path', to: "application#render_404", via: :all, constraints: lambda {|req| req.path.exclude? 'rails/active_storage'}
end

app/models/asset.rb
class Asset < ApplicationRecord
  serialize :event_tags
  belongs_to :user
  has_many :ratings, dependent: :destroy
  belongs_to :location
  has_many :requests, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy
  has_many :bookings, dependent: :destroy

  scope :sort_by_price, -> { order("price / payment_period_days") }
  scope :latest_available, -> { order(:created_at).where(available: true) }
  scope :wished_assets_of_user, ->(asset_ids) { where("id in (?)", asset_ids) } 
  
  def avg_rating
    return self.ratings.average(:score).to_f if self.ratings.any?
    0.0
  end

  def accepted_requests
    self.requests.where(request_status: 'accepted')
  end

  def self.search(search_text)
    joins(:location).where("assets.name like ? or assets.event_tags like ? or locations.place like ? or locations.city like ?",
       "%#{search_text}%", "%#{search_text}%", "%#{search_text}%", "%#{search_text}%")
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  include AssetsHelper
  before_action :ensure_authorized_user, only: [:new, :create, :destroy, :add_to_wishlist]
  before_action :phone_number_verification, only: [:new, :create, :destroy], if: :user_signed_in?
  before_action :restrict_add_to_wishlist, only: [:add_to_wishlist]
  rescue_from ActiveRecord::RecordInvalid, with: :unable_to_register_location
  before_action :set_asset, only: [:show, :destroy]

  def index
    if params[:search]
      @assets = Asset.search(params[:search])
    else
      @assets = Asset.latest_available
    end
  end

  def new
    @asset = Asset.new
  end

  def create
    @asset = Asset.new(asset_params)
    @asset.user = current_user
    @asset.payment_period_days = number_of_days(@asset.payment_period)
    @location = Location.find_or_create_by!(city: params[:city], place: params[:place], pincode: params[:pincode])
    @asset.location = @location
    @asset.event_tags = params[:event_tags].split(",")
    if @asset.save
      flash[:notice] = "Asset has been posted successfully."
      redirect_to asset_path(@asset)
    else
      flash[:alert] = "Unable to save"
      render 'assets/new'
    end
  end

  def show
  end

  def destroy
    authorize @asset
    if @asset.destroyed
      flash[:success] = "Asset has been destroyed successfully"
      redirect_to root_path
    else
      flash[:danger] = "Unable to destroy the asset"
      redirect_to asset_path(@asset)
    end
  end

  def get_option_for_search_input
    @options = generate_option_array(params[:search])
    render inline: '<%= options_for_select(' + @options.to_s + ') %>'
  end

  def add_to_wishlist
    @wishlist = create_or_assign_wishlist
    @wished_asset = @wishlist.wished_assets.create!(asset_id: params[:asset_id])
    flash[:success] = "Asset has been added to your wishlist"
    redirect_to asset_path(params[:asset_id])
  end

  def remove_from_wishlist
    current_user.wished_assets.find_by(asset_id: params[:asset_id]).delete
    current_user.wishlist.delete unless current_user.wished_assets.any?  #now use of wishlist if there is no wished_assets
    flash[:success] = "Asset has been removed from your wishlist"
    redirect_to asset_path(params[:asset_id])
  end

  def sort_and_filter_assets
    if params[:sort_by] == "price"
      @assets = Asset.sort_by_price
      render partial: "assets/asset", collection: @assets
    elsif params[:sort_by] == "distance"
      @assets = sorted_assets_by_distance(params[:coordinates], params[:distance])
      render partial: "assets/asset", collection: @assets
    end
  end

  def wished_assets
    if current_user.wishlist
      @wished_assets = current_user.wished_assets
    else
      @wished_assets = WishedAsset.none
    end
  end

  private

  def ensure_authorized_user
    redirect_to new_user_session_path unless user_signed_in?
  end

  def asset_params
    params.require(:asset).permit(:name, :dimension, :description, :currency, :price, :payment_period, :address, pictures: [])
  end

  def phone_number_verification
    redirect_to new_phone_verification_path unless current_user.phone_verification_status
  end

  def restrict_add_to_wishlist
    if current_user.id == Asset.find(params[:asset_id]).user_id
      flash[:warning] = "It's your asset"
      redirect_to asset_path(params[:asset_id])
    end
    if current_user.wishlist
      if current_user.wished_assets.find_by(asset_id: params[:asset_id])
        flash[:warning] = "Already exists in your wishlist "
        redirect_to asset_path(params[:asset_id])
      end  
    end
  end
  
  def unable_to_register_location
    flash.now[:danger] = "Unable generate coordinates for your location"
    render 'assets/new'
  end

  def set_asset
    @asset = Asset.find(params[:id])
  end

  def authorize_destroy
    @asset = Asset.find(params[:id])
    unless current_user.id.eql? @asset.user_id 
      flash[:warning] = "You are not authorized for this action"
      redirect_to asset_path(@asset)
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
  #for image crousel activity
  def active_class(index)
    return "active" if index.eql? 0
    ""
  end

  def display_avg_rating(asset)
    asset.avg_rating
  end

  def is_already_wishlisted?(asset_id)
    current_user.wished_assets.find_by(asset_id: asset_id) if user_signed_in? && current_user.wishlist
  end

  def number_of_days(in_words)
    return 1 if in_words == "Per Day"
    return 7 if in_words == "Per Week"
    return 30 if in_words == "Per Month"
    return 365 if in_words == "Per Annum"
  end
  
  def sorted_assets_by_distance(coords, distance)
    locations = Location.near(coords, distance)
    locations.inject([]) do |assets, location|
      assets += location.assets
    end
  end

  def generate_option_array(input_text)
    Array.new + Asset.where("name like ?", "%#{input_text}%").pluck(:name).uniq + 
    Asset.where("event_tags like ?", "%#{input_text}%").pluck(:event_tags).flatten.uniq + 
    Location.where("place like ?", "%#{input_text}%").pluck(:place).uniq + 
    Location.where("city like ?", "%#{input_text}%").pluck(:city).uniq 
  end

  def create_or_assign_wishlist
    return current_user.wishlist if current_user.wishlist
    current_user.create_wishlist!
  end
  
end

app/views/assets/_asset.html.erb
<div class="card asset-cards col-sm-3">
  <% if !asset.available %>
    <div class="booked-stamp-for-cards">
      <%= image_tag "booked-stamp.png", alt: "Booked stamp" %>
    </div>
  <% end %>
  <%= image_tag asset.pictures.first, alt: "Card Image", class: "card-img-top", style: "height: 13rem;" %>
  <div class="card-body">
    <h4 class="card-title"><%= asset.name %></h4>
    <div>
      <% asset.event_tags.each do |event| %>
        <span class="event"> <%= event %> </span>
      <% end %>
    </div>
    <br>
    <div class="display-address-card">
      <p class="card-text"> <%= asset.address %>  <%= asset.location.place %>, <%= asset.location.city %>, 
      <%= asset.location.pincode %></p>
    </div>
    <div class="card-footer" id="display_price">
      <%= asset.currency %> <%= asset.price %> <%= asset.payment_period %>
      <%= link_to 'See it', asset_path(asset), class: "btn btn-success col-sm-12" %>
    </div>
  </div>
</div>

app/views/assets/index.html.erb
<div class="filter-container row">
  <div class="ml-1 col-sm-2">
    <%= label_tag :sort_by_price, "Sort by price" %>
    <%= radio_button_tag :sort_by, 'price' %>
  </div>
  <div class="col-sm-3">
    <%= label_tag :sort_by_distance, "Sort by distance from current Location:" %>
    <%= radio_button_tag :sort_by, 'distance' %>
  </div>
  <div class="col-sm-2">
    <%= number_field_tag :distance_value, 5, class: "form-control", style: "margin-top: 0;", disabled: true %>
  </div>
</div> <hr>
<div class="row" id="show_assets_cards">
  <% if @assets.any? %>
    <%= render @assets %>
    <% else %>
    <h4>Oops.. Nothing yet..</h4>
  <% end %>
</div>

app/views/assets/new.html.erb
<div class="container col-sm-7 advertisement-container">
  <div class="text-center"> <h2>POST YOUR AD</h2> <hr></div>
  <%= form_for(@asset) do |f| %>
    <% if @asset.errors.any? %>
      <div class="alert alert-danger">
        <%= "Server found #{@asset.errors.count} validation errors" %>
        <% @asset.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>

    <div class="container col-sm-11" id="asset_details">
      <%= label_tag :add_asset_tags, "*Add atleat one Event tag:" %>
      <div class="view-event-tags"></div>
      <%= text_field_tag :event_tags, nil, style: "display: none;", required: true %>
      <div class="form-inline">
        <%= text_field_tag :add_asset_tags, nil, class: "form-control col-sm-9", placeholder: "E.g: Party, Parking, Sport, Get Together..", list: "suggestions" %>
        <datalist id="suggestions">
          <option value="Party"></option>
          <option value="Parking"></option>
          <option value="Sport"></option>
          <option value="Get Together"></option>
          <option value="Function"></option>
          <option value="Meeting"></option>
          <option value="Feast"></option>
          <option value="Staying"></option>
        </datalist>
        <button type="button" class="btn btn-primary col-sm-3" id="add_tags" disabled=true>Add Tag</button>
      </div>
      <h3>Enter few features and details: </h3>
      <div class="form-group">
        <%= f.label :name, "*Name Your Place:" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Give a name to your place. E.g (Peterson's Garage, Game Space)", required: true %>
        <div class="feedback-warning"></div>
      </div>
      <div class="form-group">
        <%= f.label :dimension, "*Dimensions of the Place:" %>
        <%= f.text_field :dimension, class: "form-control", placeholder: "E.g (22m X 32m, 50ft. x 20ft..)", required: true %>
        <p style="font-size: 0.7rem; color: blue;"> Enter dimension Formate: (Length x breadth) </p>
        <div class="feedback-warning"></div>
      </div>
      <div class="form-group">
        <%= f.label :description, "*Brief the Features:" %>
        <%= f.text_area :description, class: "form-control", rows: 3, placeholder: "Brief condition, features, locality and facilities (Min: 20 charecters)", required: true %>
        <p style="font-size: 0.7rem; color: blue;"> This will help viewer to have proper idea of your asset, exactly what benefits and features the user will be getting.</p>
         <div class="feedback-warning"></div>
      </div>
      <hr>
    </div>

    <div class="container col-sm-11" id="price">
      <h3>Set the pricing: </h3>
      <div class="form-group">
        <%= f.label :price, "*Price:" %>
        <div class="form-inline">
          <%= f.select(:currency, ["\u20B9", "\u20AC", "\u00A5", "\u0024", "\u20BD", "\u3350"], {}, class: "form-control col-sm-2") %>
          <%= f.text_field :price, class: "form-control col-sm-6", required: true %>
          <%= f.select(:payment_period, ["Per Day", "Per Week", "Per Month", "Per Annum"], {}, class: "form-control col-sm-4") %>
          <div class="feedback-warning"></div>
        </div>
      </div>
      <hr>
    </div>
    <div class="container col-sm-11" id="asset_images">
      <h3>Upload upto 6 images: </h3>
        <div class="asset-pictures">
          <label for="asset_pictures" class= "fa fa-plus btn btn-primary">
            Add Photos
          </label>
          <%= f.file_field :pictures, multiple: true, accept: "image/jpg, image/jpeg, image/png", required: true %>
          <div class="preview-images">
          </div>
          <div class="feedback-warning"></div>
        </div>
        <p style="font-size: 0.7rem; color: blue;">First image will be displayed while listing</p>
    </div>

    <div class="container col-sm-11" id="location_info">
      <h3>Location Details:</h3>
      <div class="form-group">
        <%= f.label :address, "*Address:" %>
        <%= f.text_field :address, placeholder: "Enter plot no., landmark, road/lane, Floor no.", class: "form-control", required: true %>
        <div class="feedback-warning"></div>
      </div>
      <div class="form-group">
        <%= label_tag :place, "*Place/Street Name:" %>
        <%= text_field_tag :place, nil, placeholder: "Area, Street or square name", class: "form-control", required: true %>
        <div class="feedback-warning"></div>
      </div>
      <div style="display: flex;">
        <div class="form-group col-sm-9" style="padding-left: 0;">
          <%= label_tag :city, "*City:"%>
          <%= text_field_tag :city, nil, placeholder: "City name", class: "form-control", required: true%>
          <div class="feedback-warning"></div>
        </div>
        <div class="form-group col-3" style="padding-right: 0;">
          <%= label_tag :pincode, "*Pincode:" %>
          <%= text_field_tag :pincode, nil, class: "form-control", required: true %>
        </div>
      </div>
    </div>
    <%= f.submit "POST AD.", class: "btn btn-primary", id: "post_ad" %>
  <% end %>
</div>

app/views/assets/show.html.erb
<div class="show-asset-container container col-sm-10">
  <div id="asset_images" class="carousel slide text-center" data-ride="carousel">
    <% unless is_already_wishlisted? @asset.id %>
      <%= link_to asset_add_to_wishlist_path(@asset), class: "btn btn-link wishlist-button" do %>
        <span class="fa fa-plus-square" style="color: #b6f769; font-size: xx-large;" title="Add to your wishlist"></span>
      <% end %>
      <% else %>
      <%= link_to asset_remove_from_wishlist_path(@asset), method: :delete, class: "btn btn-link wishlist-button" do %>
        <span class="fa fa-window-close" style="color: red; font-size: xx-large;" title="Remove from your wishlist"></span>
      <% end %> 
    <% end %>
    <!-- Indicators -->
    <ul class="carousel-indicators">
      <% @asset.pictures.count.times do |i| %>
        <li data-target="#asset_images" data-slide-to=<%= i.to_s %> class=<%= active_class(i) %> > </li>
      <% end %>
    </ul>

    <!-- slide show -->
    <div class="carousel-inner">
      <% i = 0 %>
      <% @asset.pictures.each do |img| %>
        <div class="carousel-item <%= active_class(i) %>">
          <%= image_tag img, alt: "Missing images"%>
        </div>
        <% i = i + 1 %>
      <% end %>
    </div>

    <!-- Left right controls -->
    <a href="#asset_images" data-slide="prev" class="carousel-control-prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a href="#asset_images" data-slide="next" class="carousel-control-next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
  <hr>
  <div id="asset_title"><h3><strong> <%= @asset.name %> </strong></h3></div>
  <div id="show_asset_tags">
    <% @asset.event_tags.each do |tag| %>
      <div class="show-event-tags"> <%= tag %> </div>
    <% end %>
    <hr>
  </div>
  <div class="row asset-description">
    <div class="col-sm-5" style="border-right: 1px solid black;">
      <strong>Dimension:</strong> <br>
      <%= @asset.dimension %>
    </div>
    <div class="col-sm-7">
      <strong>Features and description:</strong> <br>
      <%= @asset.description %>
    </div>
  </div>
  <hr>
  <h4>User Information</h4>
  <div class="row" id="show_owner_info">
    <div class="col-sm-2" style="padding-right: 0;">
      <%= image_tag place_user_profile_picture(@asset.user), alt: "profile picture" %>
    </div>
    <div class="col-sm-7" style="padding-left: 0;">
      <p style="margin-top: 1.5rem; margin-bottom: 0;"><%= "#{@asset.user.first_name} #{@asset.user.last_name}" %></p>
      <p style="color: blue; margin-bottom: 0;"><%= @asset.user.email %> </p>
      <p> <%= "#{@asset.user.country_code} #{@asset.user.phone_number}" %> </p>
    </div>
     
  </div>
  <hr>

  <div id="show-asset-location">
    <h4>Location Details</h4>
    <div id="asset_location_map">
      <div id="coordinates" style="display: none;"> <%= @asset.location.latitude %>, <%= @asset.location.longitude %> </div>
    </div>
    <div id="show_address" style="margin-top: 0.6rem;">
      <strong>Address:</strong> <%= @asset.address %> <br>
      <strong>Place:</strong> <%= @asset.location.place %>
      <strong>City:</strong> <%= @asset.location.city %>
      <strong>Pincode:</strong> <%= @asset.location.pincode %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm-4" style="color: orange; font-size: 1.3rem;">
      <strong><%= "#{@asset.currency}#{@asset.price} #{@asset.payment_period}" %></strong>
    </div>
    <% if @asset.available %>
      <div class="col-sm-8">
        <%= link_to "Request Booking", new_request_asset_bookings_path(@asset), class: "btn btn-primary", style: "float: right;"%>
        <%= link_to "Back", assets_path, class: "btn btn-warning", style: "float: right; margin-right: 0.5rem;" %>
      </div>
      <%= link_to 'Delete Post', asset_path(@asset), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-lg btn-danger" if policy(@asset).destroy? %>
    <% end %>  
  </div>
  <hr>
  
  <div id="show_rating"> 
    <% if display_avg_rating(@asset).class.superclass == Numeric %>
      <%= link_to asset_ratings_path(@asset) do %>
        <span class="fa fa-star checked"></span> <%= display_avg_rating(@asset) %>/5
        <span id="show_rating_click_msg">(click here to view reviews)</span>
      <% end %>
      <% else %>
      <%= display_avg_rating(@asset) %>
    <% end %>
  </div>
  <hr>
  <div class="dropdown-toggle" data-toggle="collapse" data-target="#rating_form_container" id="show_rating_form">
    Rate Here:
  </div>
  <div class="collapse" id="rating_form_container">
    <%= render 'ratings/rating_form' %>
  </div>
  <hr>
</div>


<%= javascript_pack_tag 'showAsset' %>

app/views/assets/wished_assets.html.erb
<h3>My wishlist</h3>
<hr>
<div class="row">
  <% if @wished_assets.any? %>
    <% @wished_assets.each do |wished_asset|  %>
      <%= render partial: 'assets/asset', locals: { asset: Asset.find(wished_asset.asset_id) } %>
    <% end %>
    <% else %>
    <h4>Your wishlist is empty.</h4>
  <% end %>
</div>