config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'notifications/index'
  get 'assets/index'
  devise_for :users

  get 'users/:id', to: 'users#show', as: 'show_user'
  delete 'delete_profile_picture', to: 'users#delete_profile_picture', as: 'delete_profile_picture'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :assets do
    resources :bookings do
      collection do
        post :create_request
        get :new_request
      end
    end
    collection do
      get :sort_and_filter_assets
      get :wished_assets
    end
    resources :ratings, only: [:index, :create]
    get :add_to_wishlist
    delete :remove_from_wishlist
  end
  resources :bookings, only: [:index, :destroy] do
    collection do
      get :requests
      get 'show_request/:id', to: 'bookings#show_request', as: 'show_request'
      get :requested_assets
      get 'show_request/:request_id/reject_request', to: 'bookings#reject_request', as: 'reject_request'
      get 'show_request/:request_id/accept_request', to: 'bookings#accept_request', as: 'accept_request'
      get :booked_assets
    end
  end
  resources :notes, path: 'notes/:request_id', only: [:create, :index, :destroy]

  get 'my_assets', to: 'users#assets', as: 'my_assets'
  get 'search_option', to: 'assets#get_option_for_search_input', as: 'search_option'
  root 'assets#index'

  resources :phone_verifications, only: [:new, :create] do |p|
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'

  resources :notifications, only: [:index, :update]

  match '*path', to: "application#render_404", via: :all, constraints: lambda {|req| req.path.exclude? 'rails/active_storage'}
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent N Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="icon" href="/r-icon.png">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Galindo' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.js' %>
    <%= stylesheet_link_tag 'https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" id="application_nav">
      <%= link_to 'Rent N Event', root_path, class: "navbar-brand", id: "brand_name" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <%= form_tag(assets_path, method: :get, class: "form-inline") do %>
          <div class="search-form">
            <%= text_field_tag(:search, nil, class: "form-control", placeholder: "Location or Event", list: "search_options") %>
             <datalist id="search_options"></datalist>
            <%= button_tag :submit, class: "btn btn-success" do %>
              <i class="fa fa-search"></i>
            <% end %>
          </div>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <%= link_to 'Advertise', new_asset_path, class: "nav-link btn btn-dark btn-lg fa fa-bullhorn" %>
          <% if !user_signed_in? %>
            <li class="nav-item custom-hover">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item custom-hover">
              <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
            </li>
            <% else %>
            <li class="nav-item dropdown">
              <span class="dropdown-toggle" data-toggle="dropdown"><%= image_tag place_user_profile_picture(current_user), alt: "default_profile_pic.png", id: "nav_profile_pic" %></span>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-item"> <%= current_user.first_name %> </div> <hr>
                <%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to 'My assets', my_assets_path, class: "dropdown-item" %>
                <%= link_to 'Requests for me', requested_assets_bookings_path, class: "dropdown-item" %>
                <%= link_to 'Requests by me', requests_bookings_path, class: "dropdown-item" %>
                <%= link_to 'My Bookings', bookings_path, class: "dropdown-item" %>
                <%= link_to 'My Booked Assets', booked_assets_bookings_path, class: "dropdown-item" %>
                <%= link_to 'Wishlist', wished_assets_assets_path, class: "dropdown-item" %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to notifications_path do %>
                <span class="fa fa-bell" style="font-size: 1.85rem; color: green;" id="notification_sign"> <span id="unviewed_notifications" unviewed_count=<%= get_unviewed_count %> ></span> </span>
              <% end %>
            </li>
          <% end %>
        </ul>

      </div>              
    </nav>
    <% flash.each do |key, value| %>
      <% key = key_convert(key) %>
      <div class="alert alert-<%= key.to_s %> alert-dismissible" id="alert_info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
    <% end %>

    <div class="container-fluid" id="content">
      <noscript> <h4 style="color: red;">Javascript disabled. Many features of the app maybe disabled.</h4> </noscript>
      <%= yield %>
    </div>
    <hr>
    <footer class="footer text-center">&copy; Mindfire Solutions Developer: <em>Ritik Ranjan Baidyanath</em></footer>
  </body>
</html>